server:
  servlet:
    context-path: /webExample
spring:
  #全局加载配置
  messages:
    basename: messages/globalMessages
rabbit:
  web:
    rest-packages: com.rabbitframework.example.web.rest
    request-log: true
    template-variable-path: com.rabbitframework.example.template
    freemarker-path: /freemarker
  security:
    cookie:
      name: example
      path: /
    sessionIdCookieEnabled: true
    tokenEnabled: true
      #filter-chain-definitions:
    # uriPerms: /freemarker/*
    session-dao-key-prefix: example_session_test
    realm-bean-names:
      - exampleRealm
#    session-type: local
#    cache-type: redis
  commons:
    front-black: true
    page404: false